import { Key, UnsupportedError, identityCodec, type Codec, type Database, type ExistingRecord, type QueryPage, type RecordSnapshot, type StructuredQuery, type UpdateData } from "@dal-go/dalgo";
import type { KustoDatabaseOptions, KustoParameter, KustoTable } from "./types.js";

const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/u;
type JsonObject = Record<string, unknown>;
type Scalar = string | number | boolean | null;
interface KustoFrame { readonly FrameType: unknown; readonly TableId?: unknown; readonly TableKind?: unknown; readonly Columns?: unknown; readonly Rows?: unknown; readonly HasErrors?: unknown; readonly Cancelled?: unknown; }

export class KustoHttpError extends Error { public readonly status: number; public constructor(status: number) { super(`Kusto request failed with HTTP ${String(status)}`); this.name = "KustoHttpError"; this.status = status; } }
/** Deliberately redacted token, transport, redirect, timeout, body, and response failure. */
export class KustoRequestError extends Error { public constructor() { super("Kusto request could not be completed"); this.name = "KustoRequestError"; } }

function object(value: unknown): value is JsonObject { return typeof value === "object" && value !== null && !Array.isArray(value); }
function validIdentifier(value: string, what: string): string { if (!IDENTIFIER.test(value)) throw new TypeError(`Kusto ${what} must be an ASCII identifier`); return value; }
function positive(value: number | undefined, fallback: number, what: string): number { const result = value ?? fallback; if (!Number.isSafeInteger(result) || result < 1 || result > 16_777_216) throw new TypeError(`${what} must be a positive safe integer`); return result; }
function codec<T>(value?: Codec<T>): Codec<T> { return (value ?? identityCodec) as Codec<T>; }
function stringKey(key: Key): asserts key is Key<string> { if (key.parent !== undefined || typeof key.id !== "string" || key.id.length === 0) throw new UnsupportedError("Kusto DALgo keys must be non-empty root string IDs"); }
function quoteName(name: string): string { return `[${validIdentifier(name, "identifier")}]`; }

function parameterLiteral(parameter: KustoParameter): string | number {
  if (parameter.type === "long" && (typeof parameter.value !== "number" || !Number.isSafeInteger(parameter.value))) throw new TypeError("Kusto long parameters must be safe integers");
  if (parameter.type === "long") return parameter.value as number;
  if (parameter.type === "real" && (typeof parameter.value !== "number" || !Number.isFinite(parameter.value))) throw new TypeError("Kusto real parameters must be finite numbers");
  if (parameter.type === "real") return `real(${String(parameter.value)})`;
  if (parameter.type === "bool" && typeof parameter.value !== "boolean") throw new TypeError("Kusto bool parameters must be booleans");
  if (parameter.type === "bool") return `bool(${String(parameter.value)})`;
  if (["string", "datetime", "timespan", "guid", "dynamic"].includes(parameter.type) && typeof parameter.value !== "string") throw new TypeError(`Kusto ${parameter.type} parameters must be KQL literal strings`);
  return parameter.value as string;
}

function scalar(cell: unknown): cell is Scalar { return cell === null || typeof cell === "string" || typeof cell === "boolean" || (typeof cell === "number" && Number.isFinite(cell) && (!Number.isInteger(cell) || Number.isSafeInteger(cell))); }
function abortable<T>(promise: Promise<T>, signal: AbortSignal): Promise<T> { if (signal.aborted) return Promise.reject(new KustoRequestError()); return new Promise<T>((resolve, reject) => { const abort = (): void => reject(new KustoRequestError()); signal.addEventListener("abort", abort, { once: true }); void promise.then(resolve, reject).finally(() => signal.removeEventListener("abort", abort)); }); }

function rowsFrom(value: unknown, table: KustoTable): readonly Record<string, Scalar>[] {
  if (!Array.isArray(value) || value.length < 2) throw new TypeError("malformed Kusto v2 response frames");
  const first = value[0]; const last = value.at(-1);
  if (!object(first) || first.FrameType !== "DataSetHeader" || !object(last) || last.FrameType !== "DataSetCompletion" || last.HasErrors !== false || last.Cancelled !== false) throw new TypeError("Kusto query did not complete successfully");
  const primary = value.filter((frame): frame is KustoFrame => object(frame) && frame.FrameType === "DataTable" && frame.TableKind === "PrimaryResult");
  if (primary.length !== 1) throw new TypeError("Kusto response must contain exactly one primary result table");
  const result = primary[0];
  if (result === undefined) throw new TypeError("Kusto response omitted primary result table");
  if (!Array.isArray(result.Columns) || !Array.isArray(result.Rows)) throw new TypeError("malformed Kusto primary result");
  const expected = ["__dalgo_key", ...Object.keys(table.columns)];
  if (result.Columns.length !== expected.length || result.Columns.some((column, index) => !object(column) || column.ColumnName !== expected[index] || typeof column.ColumnType !== "string")) throw new TypeError("malformed Kusto result projection");
  return result.Rows.map((row, rowIndex) => {
    if (!Array.isArray(row) || row.length !== expected.length) throw new TypeError(`malformed Kusto row ${String(rowIndex)}`);
    const record: Record<string, Scalar> = {};
    for (let index = 0; index < expected.length; index += 1) { const name = expected[index]; const cell = row[index]; if (name === undefined || !scalar(cell)) throw new TypeError("Kusto mapped values must be finite JSON scalars and safe integers"); record[name] = cell; }
    if (typeof record.__dalgo_key !== "string") throw new TypeError("Kusto key column must be string");
    return record;
  });
}

/** Read-only DALgo view over Kusto's HTTPS `/v2/rest/query` data plane. */
export class KustoDatabase implements Database {
  readonly #origin: string; readonly #database: string; readonly #accessToken: KustoDatabaseOptions["accessToken"]; readonly #tables: Readonly<Record<string, KustoTable>>; readonly #fetch: NonNullable<KustoDatabaseOptions["fetch"]>; readonly #timeoutMs: number; readonly #maxRows: number; readonly #maxResponseBytes: number;
  public constructor(options: KustoDatabaseOptions) {
    let url: URL; try { url = new URL(options.clusterUrl); } catch { throw new TypeError("clusterUrl must be an absolute URL"); }
    if (url.protocol !== "https:" || url.username || url.password || url.pathname !== "/" || url.search || url.hash) throw new TypeError("clusterUrl must be an HTTPS origin without credentials, path, query, or fragment");
    validIdentifier(options.database, "database"); if (typeof options.accessToken !== "function") throw new TypeError("accessToken must be a function");
    const tables: Record<string, KustoTable> = {};
    for (const [collection, mapping] of Object.entries(options.tables)) { validIdentifier(collection, "collection"); validIdentifier(mapping.table, "table"); validIdentifier(mapping.keyColumn, "key column"); const columns: Record<string, string> = {}; const used = new Set([mapping.keyColumn]); for (const [field, column] of Object.entries(mapping.columns)) { validIdentifier(field, "mapped field"); validIdentifier(column, "mapped column"); if (used.has(column)) throw new TypeError(`duplicate Kusto mapped column: ${column}`); used.add(column); columns[field] = column; } tables[collection] = Object.freeze({ table: mapping.table, keyColumn: mapping.keyColumn, columns: Object.freeze(columns) }); }
    this.#origin = url.origin; this.#database = options.database; this.#accessToken = options.accessToken; this.#tables = Object.freeze(tables); this.#fetch = options.fetch ?? globalThis.fetch; this.#timeoutMs = positive(options.timeoutMs, 15_000, "timeoutMs"); this.#maxRows = positive(options.maxRows, 1_000, "maxRows"); this.#maxResponseBytes = positive(options.maxResponseBytes, 1_048_576, "maxResponseBytes");
  }
  public async get<T>(key: Key, valueCodec?: Codec<T>): Promise<RecordSnapshot<T>> { stringKey(key); const table = this.table(key.collection); const rows = await this.select(table, `| where ${quoteName(table.keyColumn)} == __dalgo_key | take 2`, { __dalgo_key: { type: "string", value: key.id } }); if (rows.length === 0) return { key, exists: false }; if (rows.length !== 1) throw new KustoRequestError(); return this.snapshot(key, rows[0] ?? {}, valueCodec); }
  public async getMany<T>(keys: readonly Key[], valueCodec?: Codec<T>): Promise<readonly RecordSnapshot<T>[]> { if (keys.length === 0) return []; if (keys.length > this.#maxRows) throw new UnsupportedError("Kusto getMany above maxRows"); return Promise.all(keys.map((key) => this.get(key, valueCodec))); }
  public async query<T>(query: StructuredQuery<T>): Promise<QueryPage<T>> { if (query.source.kind !== "collection" || query.source.parent !== undefined) throw new UnsupportedError("Kusto collection-group and nested collection sources"); if (query.filters.length || query.orders.length || query.offset !== undefined || query.startAt !== undefined || query.startAfter !== undefined || query.endAt !== undefined || query.endBefore !== undefined) throw new UnsupportedError("Kusto generic DALgo filters, order, offsets, and cursors"); const requested = query.limit ?? this.#maxRows; if (!Number.isSafeInteger(requested) || requested < 1 || requested >= this.#maxRows) throw new UnsupportedError("Kusto query limit"); const table = this.table(query.source.name); const rows = await this.select(table, `| take ${String(requested + 1)}`, {}); if (rows.length > requested) throw new UnsupportedError("Kusto query continuation is required; cursor paging is unsupported"); const records = rows.map((row) => this.snapshot(new Key(query.source.name, row.__dalgo_key as string), row, query.source.codec) as ExistingRecord<T>); return { records }; }
  /** Executes caller-supplied read-only KQL with declared, typed request parameters; it returns one validated primary table. */
  public async queryKql(csl: string, parameters: Readonly<Record<string, KustoParameter>> = {}): Promise<readonly Record<string, Scalar>[]> { if (typeof csl !== "string" || csl.trim().length === 0 || csl.includes("\u0000") || /^\s*\./u.test(csl)) throw new TypeError("queryKql accepts a non-management KQL query"); const declarations = Object.entries(parameters).map(([name, parameter]) => { validIdentifier(name, "parameter name"); parameterLiteral(parameter); return `${name}:${parameter.type}`; }); const prefix = declarations.length === 0 ? "" : `declare query_parameters(${declarations.join(", ")}); `; return this.raw(`${prefix}${csl}`, parameters, undefined); }
  public async insert<T>(key: Key, data: T, valueCodec?: Codec<T>): Promise<void> { void key; void data; void valueCodec; throw new UnsupportedError("Kusto DALgo inserts: this adapter only invokes read-only query endpoint"); }
  public async set<T>(key: Key, data: T, valueCodec?: Codec<T>): Promise<void> { void key; void data; void valueCodec; throw new UnsupportedError("Kusto DALgo replacements: this adapter only invokes read-only query endpoint"); }
  public async update(key: Key, data: UpdateData): Promise<void> { void key; void data; throw new UnsupportedError("Kusto DALgo updates: this adapter only invokes read-only query endpoint"); }
  public async delete(key: Key): Promise<void> { void key; throw new UnsupportedError("Kusto DALgo deletes: this adapter only invokes read-only query endpoint"); }
  public async runReadwriteTransaction<Result>(callback: (transaction: never) => Promise<Result>): Promise<Result> { void callback; throw new UnsupportedError("Kusto callback transactions"); }
  private table(collection: string): KustoTable { const table = this.#tables[collection]; if (table === undefined) throw new UnsupportedError(`Kusto collection is not mapped: ${collection}`); return table; }
  private async select(table: KustoTable, suffix: string, parameters: Readonly<Record<string, KustoParameter>>): Promise<readonly Record<string, Scalar>[]> { const projection = [`__dalgo_key = ${quoteName(table.keyColumn)}`, ...Object.entries(table.columns).map(([field, column]) => `${quoteName(column)} as ${quoteName(field)}`)].join(", "); const declarations = Object.entries(parameters).map(([name, parameter]) => { validIdentifier(name, "parameter name"); parameterLiteral(parameter); return `${name}:${parameter.type}`; }); const prefix = declarations.length === 0 ? "" : `declare query_parameters(${declarations.join(", ")}); `; return this.raw(`${prefix}${quoteName(table.table)} | project ${projection} ${suffix}`, parameters, table); }
  private snapshot<T>(key: Key<string>, row: Record<string, Scalar>, valueCodec?: Codec<T>): RecordSnapshot<T> { const data = { ...row }; delete data.__dalgo_key; return { key, exists: true, data: codec(valueCodec).decode(data) }; }
  private async raw(csl: string, parameters: Readonly<Record<string, KustoParameter>>, table: KustoTable | undefined): Promise<readonly Record<string, Scalar>[]> { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.#timeoutMs); try { const token = await abortable(this.token(), controller.signal); const values: Record<string, string | number> = {}; for (const [name, parameter] of Object.entries(parameters)) values[name] = parameterLiteral(parameter); const response = await abortable(Promise.resolve().then(() => this.#fetch(new URL("/v2/rest/query", this.#origin), { method: "POST", redirect: "error", signal: controller.signal, headers: { accept: "application/json", "content-type": "application/json; charset=utf-8", authorization: `Bearer ${token}`, "x-ms-readonly": "true" }, body: JSON.stringify({ db: this.#database, csl, properties: { Parameters: values } }) })), controller.signal); if (!response.ok) { void response.body?.cancel().catch(() => undefined); throw new KustoHttpError(response.status); } const body = await this.body(response, controller.signal); const parsed = JSON.parse(body) as unknown; if (table === undefined) return this.genericRows(parsed); return rowsFrom(parsed, table); } catch (error) { if (error instanceof KustoHttpError || error instanceof UnsupportedError) throw error; throw new KustoRequestError(); } finally { clearTimeout(timer); } }
  private async token(): Promise<string> { try { const token = await this.#accessToken(); if (typeof token !== "string" || token.trim() === "" || /[\r\n]/u.test(token)) throw new Error(); return token; } catch { throw new KustoRequestError(); } }
  private async body(response: Response, signal: AbortSignal): Promise<string> { const length = response.headers.get("content-length"); if (length !== null && (!/^\d+$/u.test(length) || Number(length) > this.#maxResponseBytes)) { void response.body?.cancel().catch(() => undefined); throw new KustoRequestError(); } if (response.body === null) throw new KustoRequestError(); const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let size = 0; try { for (;;) { const next = await abortable(reader.read(), signal); if (next.done) break; size += next.value.byteLength; if (size > this.#maxResponseBytes) { void reader.cancel().catch(() => undefined); throw new KustoRequestError(); } chunks.push(next.value); } } finally { if (signal.aborted) void reader.cancel().catch(() => undefined); try { reader.releaseLock(); } catch { /* hostile stream */ } } const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder().decode(bytes); }
  private genericRows(value: unknown): readonly Record<string, Scalar>[] { if (!Array.isArray(value) || !object(value[0]) || value[0].FrameType !== "DataSetHeader") throw new KustoRequestError(); const completion = value.at(-1); if (!object(completion) || completion.FrameType !== "DataSetCompletion" || completion.HasErrors !== false || completion.Cancelled !== false) throw new KustoRequestError(); const frames = value.filter((item): item is KustoFrame => object(item) && item.FrameType === "DataTable" && item.TableKind === "PrimaryResult"); const frame = frames[0]; if (frames.length !== 1 || frame === undefined || !Array.isArray(frame.Columns) || !Array.isArray(frame.Rows)) throw new KustoRequestError(); const names = frame.Columns.map((column) => { if (!object(column) || typeof column.ColumnName !== "string") throw new KustoRequestError(); return column.ColumnName; }); if (new Set(names).size !== names.length) throw new KustoRequestError(); return frame.Rows.map((row) => { if (!Array.isArray(row) || row.length !== names.length) throw new KustoRequestError(); const result: Record<string, Scalar> = {}; for (let index = 0; index < names.length; index += 1) { const cell = row[index]; const name = names[index]; if (name === undefined || !scalar(cell)) throw new KustoRequestError(); result[name] = cell; } return result; }); }
}
